# Generated by Django 5.1.6 on 2025-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
