# Generated by Django 5.1.6 on 2025-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actors_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='slug',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
